name: windo_ecom
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bottom_bar_matu: ^1.3.0
  line_icons: ^2.0.3
  badges: ^3.1.2
  advance_notification: ^1.0.6
  animate_do: ^3.1.2
  carousel_slider: ^4.2.1

  get: ^4.6.6
  velocity_x: ^4.1.1
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  image_picker: ^0.8.7+5
  font_awesome_flutter: ^10.4.0
  permission_handler: ^10.4.3
  camera: ^0.10.5+2
  full_screen_image: ^2.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  image_cropper: ^5.0.0
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  clipboard: ^0.1.3
  path_provider: ^2.1.1
  open_file: ^3.3.2
  flutter_local_notifications: ^15.1.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf
